# Generated by Django 5.0.7 on 2024-07-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='n_left',
            new_name='nested_left',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='n_parent',
            new_name='nested_parent',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='n_right',
            new_name='nested_right',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='n_row',
            new_name='nested_row',
        ),
    ]
