# Generated by Django 5.0.7 on 2024-07-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_n_left_category_nested_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nested_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='nested_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='nested_row',
            field=models.IntegerField(default=0),
        ),
    ]
