# Generated by Django 5.0.7 on 2024-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_nested_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nested_child_count',
            field=models.IntegerField(default=0),
        ),
    ]
