# Generated by Django 5.0.7 on 2024-11-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_nested_child_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nested_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
